stages:
  - build_back
  - deploy

before_script:
  - chmod +x gradlew

back:
  image: openjdk:11
  stage: build_back
  only:
  - main
  script: ./gradlew -s bootJar
  artifacts:
    paths:
      - back/build/libs/back-0.0.1-SNAPSHOT.jar

production:
  stage: deploy
  only:
  - main
  script:
  - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
  - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io
  - ./cf push
